# Generated by Django 4.2.6 on 2023-11-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageList",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("m_type", models.IntegerField()),
                ("t_type", models.IntegerField()),
                ("time", models.BigIntegerField()),
                ("content", models.TextField()),
                ("sender", models.IntegerField()),
                ("receiver", models.IntegerField()),
                ("info", models.CharField(default="", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=128)),
                ("userEmail", models.EmailField(max_length=128, unique=True)),
                (
                    "avatar",
                    models.CharField(
                        default="https://images.unsplash.com/photo-1642921131008-b13897b36d17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8JUU2JUI4JTg1JUU1JThEJThFJUU1JUE0JUE3JUU1JUFEJUE2fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
                        max_length=256,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroupList",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(default="群聊", max_length=32)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "group_avatar",
                    models.CharField(
                        default="https://images.unsplash.com/photo-1642921131008-b13897b36d17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8JUU2JUI4JTg1JUU1JThEJThFJUU1JUE0JUE3JUU1JUFEJUE2fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
                        max_length=256,
                    ),
                ),
                (
                    "group_members",
                    models.ManyToManyField(
                        related_name="group_members", to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("state", models.IntegerField(default=0)),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user1_friendships",
                        to="users.user",
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user2_friendships",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user1", "user2")},
            },
        ),
    ]
