# Generated by Django 4.2.6 on 2023-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupList",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(default="群聊", max_length=32)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "group_avatar",
                    models.CharField(
                        default="https://images.unsplash.com/photo-1642921131008-b13897b36d17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8JUU2JUI4JTg1JUU1JThEJThFJUU1JUE0JUE3JUU1JUFEJUE2fGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
                        max_length=256,
                    ),
                ),
                (
                    "group_members",
                    models.ManyToManyField(
                        related_name="group_members", to="users.user"
                    ),
                ),
            ],
        ),
    ]
