# Generated by Django 4.2.6 on 2023-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_messagelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelist",
            name="time",
            field=models.BigIntegerField(),
        ),
    ]
