# Generated by Django 4.2.6 on 2023-10-17 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_friendship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
