# Generated by Django 4.2.6 on 2023-12-07 06:25

from django.db import migrations, models
import django.db.models.deletion
import utils.data


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_messagelist_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouplist",
            name="group_admin",
            field=models.ManyToManyField(related_name="group_admin", to="users.user"),
        ),
        migrations.AddField(
            model_name="grouplist",
            name="group_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_owner",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="grouplist",
            name="group_top_message",
            field=models.ManyToManyField(
                related_name="group_top_message", to="users.messagelist"
            ),
        ),
        migrations.AddField(
            model_name="messagelist",
            name="deleted_users",
            field=models.ManyToManyField(related_name="deleted_users", to="users.user"),
        ),
        migrations.AddField(
            model_name="messagelist",
            name="status",
            field=models.IntegerField(default=utils.data.MessageStatusType["NORMAL"]),
        ),
        migrations.AddField(
            model_name="messagelist",
            name="who_read",
            field=models.ManyToManyField(related_name="who_read", to="users.user"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="user",
            name="verification",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grouplist",
            name="group_avatar",
            field=models.CharField(
                default="22933c1646d1f0042e39d7471e42f33b", max_length=256
            ),
        ),
        migrations.AlterField(
            model_name="messagelist",
            name="receiver",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="22933c1646d1f0042e39d7471e42f33b", max_length=256
            ),
        ),
    ]
