# Generated by Django 4.2.6 on 2023-12-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_messagelist_who_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagelist",
            name="who_reply",
            field=models.ManyToManyField(
                related_name="related_messages", to="users.messagelist"
            ),
        ),
    ]
