# Generated by Django 4.2.6 on 2023-12-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_messagelist_who_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouplist",
            name="group_candidate_members",
            field=models.ManyToManyField(
                related_name="group_candidate_members", to="users.user"
            ),
        ),
    ]
