# Generated by Django 4.2.6 on 2023-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_grouplist_group_candidate_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyMailList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("verification_code", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="messagelist",
            name="who_reply",
            field=models.ManyToManyField(
                related_name="referenced_by", to="users.messagelist"
            ),
        ),
    ]
