# Generated by Django 4.2.6 on 2023-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_verifymaillist_alter_messagelist_who_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginMailList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=128, unique=True)),
                ("verification_code", models.IntegerField(default=0)),
            ],
        ),
    ]
