# Generated by Django 4.2.6 on 2023-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_verifymaillist_verification_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdMaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_id", models.IntegerField(default=0)),
            ],
        ),
    ]
