# Generated by Django 4.2.6 on 2023-12-19 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_idmaker"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IdMaker",
            new_name="IdMakerModel",
        ),
    ]
