# Generated by Django 4.2.6 on 2023-12-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_rename_idmaker_idmakermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaxId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_id_value", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="IdMakerModel",
        ),
    ]
