# Generated by Django 4.2.6 on 2023-12-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_maxid_delete_idmakermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                default="305565140d47daa479897e08e152c477", max_length=256
            ),
        ),
    ]
