# Generated by Django 4.2.6 on 2023-12-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginmaillist",
            name="verification_time",
            field=models.BigIntegerField(default=0),
        ),
    ]
