# Generated by Django 4.2.6 on 2023-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Multimedia",
            fields=[
                (
                    "multimedia_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("multimedia_type", models.IntegerField()),
                (
                    "multimedia_group_listener",
                    models.ManyToManyField(
                        related_name="multimedia_group_listener", to="users.grouplist"
                    ),
                ),
                (
                    "multimedia_user_listener",
                    models.ManyToManyField(
                        related_name="multimedia_user_listener", to="users.user"
                    ),
                ),
            ],
        ),
    ]
